name: Smoke test

on:
  push:
    branches: [ master, main ]
  pull_request:

concurrency:
  group: smoke-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]  # PyEphem の互換性を考慮して控えめに
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          python -m pip install -U pip
          python -m pip install . pytest
      - name: Show env
        run: |
          python -V
          python -c "import sys,platform; print(platform.platform()); print(sys.executable)"
      - name: Run smoke tests
        run: python -m pytest -q
